#!/bin/bash

max_usage=90
bar_width=50
white="\e[39m"
green="\e[1;32m"
red="\e[1;31m"
dim="\e[2m"
undim="\e[0m"

mapfile -t dfs < <(sudo df -h --total -x zfs -x squashfs -x tmpfs -x devtmpfs -x overlay -x shm --output=target,pcent,size | grep ^total)
printf "\ndisk usage:\n"

for line in "${dfs[@]}"; do
  usage=$(echo "$line" | awk '{print $2}' | sed 's/%//')
  used_width=$(((usage * bar_width) / 100))
  if [ "${usage}" -ge "${max_usage}" ]; then
    color=$red
  else
    color=$green
  fi
  bar="[${color}"
  for ((i = 0; i < used_width; i++)); do
    bar+="="
  done
  bar+="${white}${dim}"
  for ((i = used_width; i < bar_width; i++)); do
    bar+="="
  done
  bar+="${undim}]"
  echo "${line}" | awk '{ printf("%-31s%+3s used out of %+4s\n", $1, $2, $3); }' | sed -e 's/^/  /'
  echo -e "${bar}" | sed -e 's/^/  /'
done
