#!/bin/bash

COLUMNS=3
green="\e[1;32m"
red="\e[1;31m"
undim="\e[0m"

services=("docker" "wg-quick@wg0.service")
IFS=$'\n' services=($(sort <<<"${services[*]}"))
unset IFS

service_status=()
for service in "${services[@]}"; do
  service_status+=($(systemctl is-active "$service"))
done

out=""
for i in ${!services[@]}; do
  if [[ "${service_status[$i]}" == "active" ]]; then
    out+="${services[$i]}:,${green}${service_status[$i]}${undim},"
  else
    out+="${services[$i]}:,${red}${service_status[$i]}${undim},"
  fi
  if [ $((($i + 1) % $COLUMNS)) -eq 0 ]; then
    out+="\n"
  fi
done
out+="\n"

printf "\nservices:\n"
printf "$out" | column -ts $',' | sed -e 's/^/  /'
