#!/bin/bash

ips=$(ip -o addr show up scope global |  grep -Ev "br-|wg0|docker0|flannel-wg|cni0")

echo "IP addresses:"

echo "$ips" | while read -r line; do
    ip=$(echo "$line" | awk '{print $4}')
    network=$(echo "$line" | awk '{print $2}')
    echo "  $network: $ip"
done
