name: Sync Secrets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # run every day at midnight

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Update Secrets
        uses: google/secrets-sync-action@v1.7.1
        with:
          dry_run: false
          secrets: |
            ^DOCKER_PASSWORD$
            ^DOCKER_USERNAME$
            ^KUBE_CONFIG$
          repositories: |
            ^Zekihan/dockerfiles$
          github_token: ${{ secrets.SYNC_SECRETS_GH_TOKEN }}
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
